### ISSUE TITLE
Add and unify licensing information

### ISSUE THREAD

**Issue by phoe** [Refsheet/refsheet-site#238]
Am I allowed to use the Refsheet software to spin up a new personal instance of the site? If yes, then under what terms? There is no LICENSE file that describes this.

The existing source code seems to list two contradictory pieces of licensing information. One of them mentions the MIT license:

https://github.com/Refsheet/refsheet-site/blob/4afe3b15dc08825ef2d96f99254d81fdd65ff01c/package.json#L2

Whereas the other implies that the website's software cannot be used outside its main deployment:

https://github.com/Refsheet/refsheet-site/blob/4afe3b15dc08825ef2d96f99254d81fdd65ff01c/app/views/static/terms.html.haml#L20-L35

**Comment by MauAbata** [comment]
I've been attempting to find a license which properly conveys my intent with providing the source code for this website. I do not intend to permit the following:

- Commercial use of Refsheet.net code, in whole or in part,
- Publicly hosted clones of the website, which includes unauthorized mirrors,
- Public or private usage of any Refsheet.net asset which displays our brand, except where required for development and testing,

The source of Refsheet.net is provided with the following permitted intent:

- Users are permitted to save a copy for private experimentation or development only, and such a server may not be public facing
- Contributors assign copyright for their contributions to Refsheet.net for use in the main officially hosted instance and its authorized clones


So keeping with my intent in listing this software publicly, you can have a private hosted copy of Refsheet.net, but it may not be accessible to the general public. The licenses in the package.json were a default selection, and MIT is great for library code and components that build other projects, but actually isn't suitable for this package as a whole, which is the end product without derivatives. The license field in package.json also applies if this package were published to NPM, which it is not.

The license information in the terms of service page applies to any assets delivered from the public servers, which includes the minified JavaScript and user-contributed content as well as dynamic content which isn't present in the source code and exists only in production.

When I find time, I will attempt to provide a proper license for this code.
